name: 🤖 Android Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: '4.2'
  SCONSFLAGS: debug_symbols=no verbose=yes use_static_cpp=yes lto=auto
concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-android
  cancel-in-progress: true

jobs:
  build-android:
    runs-on: "ubuntu-20.04"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Release Template (arm32)
            cache-name: android-release-template_arm32
            target: template_release
            tests: false
            sconsflags: optimize=speed_trace arch=arm32

          - name: Debug Template (arm32)
            cache-name: android-debug-template_arm32
            target: template_debug
            tests: false
            sconsflags: optimize=speed_trace arch=arm32

          - name: Release Template (arm64)
            cache-name: android-release-template_arm64
            target: template_release
            tests: false
            sconsflags: optimize=speed_trace arch=arm64

          - name: Debug Template (arm64)
            cache-name: android-debug-template_arm64
            target: template_debug
            tests: false
            sconsflags: optimize=speed_trace arch=arm64

    steps:
      - uses: actions/checkout@v3

      - name: Set up Java 11
        uses: actions/setup-java@v3
        with:
          distribution: temurin
          java-version: 11

      - name: Setup Pixel Engine build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: android
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Generate Pixel Engine templates
        run: |
          cd platform/android/java
          ./gradlew generateGodotTemplates
          cd ../../..
          ls -l bin/

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      # - name: Upload release
      #   uses: ./.github/actions/upload-release
      #   with:
      #     name: ${{ matrix.cache-name }}