name: 🍏 iOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  GODOT_BASE_BRANCH: '4.2'
  SCONSFLAGS: debug_symbols=no verbose=yes use_static_cpp=yes lto=auto

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-ios
  cancel-in-progress: true

jobs:
  build-ios:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Release Template
            cache-name: ios-release-template
            target: template_release
            tests: false
            sconsflags: optimize=speed_trace

          - name: Debug Template
            cache-name: ios-debug-template
            target: template_debug
            tests: false
            sconsflags: optimize=speed_trace

    steps:
      - uses: actions/checkout@v4

      - name: Setup Pixel Engine build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }} ${{ matrix.sconsflags }}
          platform: ios
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      # - name: Upload release
      #   uses: ./.github/actions/upload-release
      #   with:
      #     name: ${{ matrix.cache-name }}