name: 🍎 macOS Builds
on:
  workflow_call:

# Global Settings
env:
  # Used for the cache key. Add version suffix to force clean build.
  PIXEL_BASE_BRANCH: '4.2'
  SCONSFLAGS: verbose=yes optimize=speed_trace use_static_cpp=yes lto=auto

concurrency:
  group: ci-${{github.actor}}-${{github.head_ref || github.run_number}}-${{github.ref}}-macos
  cancel-in-progress: true

jobs:
  build-macos:
    runs-on: "macos-latest"
    name: ${{ matrix.name }}
    strategy:
      fail-fast: false
      matrix:
        include:
          - name: Editor
            cache-name: macos-editor
            target: editor
            tests: false
            # bin: "./bin/godot.macos.editor.x86_64"

          - name: Release Template
            cache-name: macos-release-template
            target: template_release
            tests: false
            sconsflags: debug_symbols=no

          - name: Debug Template
            cache-name: macos-debug-template
            target: template_debug
            tests: false
            sconsflags: debug_symbols=no

    steps:
      - uses: actions/checkout@v4

      - name: Setup Godot build cache
        uses: ./.github/actions/godot-cache
        with:
          cache-name: ${{ matrix.cache-name }}
        continue-on-error: true

      - name: Setup python and scons
        uses: ./.github/actions/godot-deps

      - name: Compilation
        uses: ./.github/actions/godot-build
        with:
          sconsflags: ${{ env.SCONSFLAGS }}
          platform: macos
          target: ${{ matrix.target }}
          tests: ${{ matrix.tests }}

      # # Execute unit tests for the editor
      # - name: Unit tests
      #   if: ${{ matrix.tests }}
      #   run: |
      #     ${{ matrix.bin }} --version
      #     ${{ matrix.bin }} --help
      #     ${{ matrix.bin }} --test

      - name: Prepare artifact
        run: |
          strip bin/godot.*
          chmod +x bin/godot.*

      - name: Upload artifact
        uses: ./.github/actions/upload-artifact
        with:
          name: ${{ matrix.cache-name }}

      # - name: Upload release
      #   uses: ./.github/actions/upload-release
      #   with:
      #     name: ${{ matrix.cache-name }}